### ISSUE TITLE
Wrong wand capability.

### ISSUE THREAD

**Issue by XM666-Dev** [DrChaleceCume/index_core#7]
This wand is 4 slots capability but can only edit 2 slots.
It seems that the always cast spell has some problems...
![shot_20240129-134053-1337634340--288-1262-00099434](https://github.com/DrChaleceCume/index_core/assets/99076011/ef6d74f7-2645-43d2-86e1-b1fb79f8402d)
![shot_20240129-134057-1337634340--232-1263-00099601](https://github.com/DrChaleceCume/index_core/assets/99076011/774dc449-18d6-43d0-9e59-c1fa5a5dca12)

**Comment by re-coilless** [comment]
I'll comment on this in anyways: in vanilla, always casts spells are not considered real spells yet they literally are. When an always cast spell is attached to a wand, it gains an extra slot, but the mere presence of permanently attached modifier subtracts from the displayed slot count.
So, I made a decision that, since I show AC spells as being actual, I might as well leave the slot count be its true self. Additionally, it is possible to allow proper editing of locked modifiers within this framework, so it's only fair.

**Comment by re-coilless** [comment]
Also, what's with this invisible wand? Could you provide the mod it's from, so I can look into it?

**Comment by XM666-Dev** [comment]
Please fix this, it's from [Wizardly Weapons Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2840569867).
Index mod makes some wands from this mod become invisible.
